-- Para a base de dados IDH:

-- 1 - Municípios que não pertencem a região norte

SELECT M.CODMUNICIPIO, M.NOMEMUNICIPIO, M.CODESTADO FROM MUNICIPIO AS M
	INNER JOIN ESTADO AS E
		ON(M.CODESTADO = E.CODESTADO)
	INNER JOIN REGIAO AS R
		ON(E.CODREGIAO = R.CODREGIAO)
WHERE R.CODREGIAO != 1;

SELECT * FROM MUNICIPIO AS M
WHERE M.CODESTADO 
	IN (SELECT E.CODESTADO FROM ESTADO AS E
		WHERE E.CODREGIAO IN
		(SELECT R.CODREGIAO FROM REGIAO AS R));

SELECT * FROM MUNICIPIO AS M
WHERE EXISTS (SELECT E.CODESTADO FROM ESTADO AS E
				WHERE EXISTS
				(SELECT R.CODREGIAO FROM REGIAO AS R));

-- 2 - Municípios que possuem o mesmo nome

SELECT * FROM MUNICIPIO
WHERE EXISTS (SELECT NOMEMUNICIPIO FROM MUNICIPIO
				GROUP BY NOMEMUNICIPIO
				HAVING COUNT(*) > 1);

-- 3 - Média de municípios por Região

SELECT AVG(QTDMUNICIPIO) FROM
	(SELECT COUNT(*) AS QTDMUNICIPIO FROM MUNICIPIO AS M
		INNER JOIN ESTADO AS E
			ON(E.CODESTADO = M.CODESTADO)
		INNER JOIN REGIAO AS R
			ON(R.CODREGIAO = E.CODREGIAO)
	GROUP BY R.CODREGIAO);

SELECT AVG(QTDMUNICIPIO) FROM
	(SELECT COUNT(*) AS QTDMUNICIPIO FROM MUNICIPIO AS M, ESTADO AS E, REGIAO AS R
		WHERE M.CODESTADO = E.CODESTADO AND E.CODREGIAO = R.CODREGIAO
	GROUP BY R.CODREGIAO);

-- 4 - Sigla dos estados com as respectivas quantidades de municípios

SELECT E.SIGLAESTADO, COUNT(*) FROM ESTADO AS E
	INNER JOIN MUNICIPIO AS M
		ON(E.CODESTADO = M.CODESTADO)
	GROUP BY E.SIGLAESTADO;

SELECT E.SIGLAESTADO, COUNT(*) FROM ESTADO AS E, MUNICIPIO AS M
WHERE E.CODESTADO = M.CODESTADO
GROUP BY E.SIGLAESTADO; 

-- 5 - Município com as pessoas mais idosas

SELECT * FROM MUNICIPIO
	WHERE CODMUNICIPIO = (SELECT CODMUNICIPIO FROM INDICE
							WHERE IDH_LONGEVIDADE = (SELECT MAX(IDH_LONGEVIDADE) FROM INDICE));

SELECT M.CODMUNICIPIO, M.NOMEMUNICIPIO, M.CODESTADO FROM MUNICIPIO AS M
	INNER JOIN INDICE AS I
		ON(I.CODMUNICIPIO = M.CODMUNICIPIO)
WHERE I.IDH_LONGEVIDADE = (SELECT MAX(IDH_LONGEVIDADE) FROM INDICE);

SELECT M.CODMUNICIPIO, M.NOMEMUNICIPIO, M.CODESTADO FROM MUNICIPIO AS M
	INNER JOIN INDICE AS I
		ON(I.CODMUNICIPIO = M.CODMUNICIPIO)
WHERE I.IDH_LONGEVIDADE IN (SELECT MAX(IDH_LONGEVIDADE) FROM INDICE);

-- 6 - Ano em que Salvador obteve o melhor índice de Instrução

SELECT ANO FROM INDICE
WHERE (CODMUNICIPIO, IDH_EDUCACAO) IN
	(SELECT CODMUNICIPIO, MAX(IDH_EDUCACAO) FROM INDICE
				GROUP BY CODMUNICIPIO)
	AND CODMUNICIPIO IN 
		(SELECT CODMUNICIPIO FROM MUNICIPIO
			WHERE NOMEMUNICIPIO = 'Salvador');

-- 7 - Qual o município com a melhor distribuição de renda
-- 8 - Quais estados possuem municípios com IDH geral maior que 0,8
-- 9 - Qual o maior IDH de educação por estado
-- 10- Relatório de Todos IDHs da Bahia de 91 e 2000, inclusive com a
-- diferença entre os mesmos
-- 11 - Relatório comparativo entre as médias dos IDHs de SC e AL,
-- de 2000 e 91

