-- Para a base de dados IDH:

-- 1 - Municípios que não pertencem a região norte
EXPLAIN ANALYZE
SELECT DISTINCT M.CODMUNICIPIO, M.NOMEMUNICIPIO, M.CODESTADO FROM MUNICIPIO AS M
	INNER JOIN ESTADO AS E
		ON(M.CODESTADO = E.CODESTADO)
	INNER JOIN REGIAO AS R
		ON(E.CODREGIAO = R.CODREGIAO)
WHERE R.CODREGIAO != (SELECT MAX(R.CODREGIAO) FROM REGIAO AS R WHERE NOMEREGIAO != 'Norte');

EXPLAIN ANALYZE
SELECT * FROM MUNICIPIO AS M
WHERE M.CODESTADO 
	IN (SELECT E.CODESTADO FROM ESTADO AS E
		WHERE E.CODREGIAO IN
		(SELECT R.CODREGIAO FROM REGIAO AS R WHERE NOMEREGIAO != 'Norte'));

EXPLAIN ANALYZE
SELECT * FROM MUNICIPIO AS M
WHERE EXISTS (SELECT E.CODESTADO FROM ESTADO AS E
				WHERE EXISTS
				(SELECT R.CODREGIAO FROM REGIAO AS R WHERE NOMEREGIAO != 'Norte'));

-- 2 - Municípios que possuem o mesmo nome
EXPLAIN ANALYZE
SELECT * FROM MUNICIPIO
WHERE EXISTS (SELECT NOMEMUNICIPIO FROM MUNICIPIO
				GROUP BY NOMEMUNICIPIO
				HAVING COUNT(*) > 1);

-- 3 - Média de municípios por Região
EXPLAIN ANALYZE
SELECT AVG(QTDMUNICIPIO) FROM
	(SELECT COUNT(*) AS QTDMUNICIPIO FROM MUNICIPIO AS M
		INNER JOIN ESTADO AS E
			ON(E.CODESTADO = M.CODESTADO)
		INNER JOIN REGIAO AS R
			ON(R.CODREGIAO = E.CODREGIAO)
	GROUP BY R.CODREGIAO);

EXPLAIN ANALYZE
SELECT AVG(QTDMUNICIPIO) FROM
	(SELECT COUNT(*) AS QTDMUNICIPIO FROM MUNICIPIO AS M, ESTADO AS E, REGIAO AS R
		WHERE M.CODESTADO = E.CODESTADO AND E.CODREGIAO = R.CODREGIAO
	GROUP BY R.CODREGIAO);

-- 4 - Sigla dos estados com as respectivas quantidades de municípios
EXPLAIN ANALYZE
SELECT E.SIGLAESTADO, COUNT(*) FROM ESTADO AS E
	INNER JOIN MUNICIPIO AS M
		ON(E.CODESTADO = M.CODESTADO)
	GROUP BY E.SIGLAESTADO;

EXPLAIN ANALYZE
SELECT E.SIGLAESTADO, COUNT(*) FROM ESTADO AS E, MUNICIPIO AS M
WHERE E.CODESTADO = M.CODESTADO
GROUP BY E.SIGLAESTADO; 

-- 5 - Município com as pessoas mais idosas
EXPLAIN ANALYZE
SELECT * FROM MUNICIPIO
	WHERE CODMUNICIPIO = (SELECT CODMUNICIPIO FROM INDICE
							WHERE IDH_LONGEVIDADE = (SELECT MAX(IDH_LONGEVIDADE) FROM INDICE));

EXPLAIN ANALYZE
SELECT M.CODMUNICIPIO, M.NOMEMUNICIPIO, M.CODESTADO FROM MUNICIPIO AS M
	INNER JOIN INDICE AS I
		ON(I.CODMUNICIPIO = M.CODMUNICIPIO)
WHERE I.IDH_LONGEVIDADE = (SELECT MAX(IDH_LONGEVIDADE) FROM INDICE);

EXPLAIN ANALYZE
SELECT M.CODMUNICIPIO, M.NOMEMUNICIPIO, M.CODESTADO FROM MUNICIPIO AS M
	INNER JOIN INDICE AS I
		ON(I.CODMUNICIPIO = M.CODMUNICIPIO)
WHERE I.IDH_LONGEVIDADE IN (SELECT MAX(IDH_LONGEVIDADE) FROM INDICE);

-- 6 - Ano em que Salvador obteve o melhor índice de Instrução
EXPLAIN ANALYZE
SELECT ANO FROM INDICE
WHERE (CODMUNICIPIO, IDH_EDUCACAO) IN
	(SELECT CODMUNICIPIO, MAX(IDH_EDUCACAO) FROM INDICE
				GROUP BY CODMUNICIPIO)
	AND CODMUNICIPIO IN 
		(SELECT CODMUNICIPIO FROM MUNICIPIO
			WHERE NOMEMUNICIPIO = 'Salvador');

-- 7 - Qual o município com a melhor distribuição de renda
EXPLAIN ANALYZE
SELECT * FROM MUNICIPIO
WHERE CODMUNICIPIO IN (SELECT CODMUNICIPIO FROM INDICE
						WHERE IDH_RENDA IN (SELECT MAX(IDH_RENDA) FROM INDICE));

-- MELHOR QUERY
EXPLAIN ANALYZE
SELECT M.CODMUNICIPIO, M.NOMEMUNICIPIO, M.CODESTADO FROM MUNICIPIO AS M
	INNER JOIN INDICE AS I
		ON(M.CODMUNICIPIO = I.CODMUNICIPIO)
WHERE I.IDH_RENDA = (SELECT MAX(IDH_RENDA) FROM INDICE);

-- 8 - Quais estados possuem municípios com IDH geral maior que 0,8
EXPLAIN ANALYZE
SELECT NOMEESTADO FROM ESTADO
WHERE CODESTADO IN 
	(SELECT CODESTADO FROM MUNICIPIO WHERE CODMUNICIPIO IN 
	(SELECT CODMUNICIPIO FROM INDICE WHERE IDH_GERAL > 0.8));	

-- 9 - Qual o maior IDH de educação por estado
EXPLAIN ANALYZE
SELECT E.NOMEESTADO, MAX(I.IDH_EDUCACAO) FROM ESTADO AS E
	INNER JOIN MUNICIPIO AS M
		ON(E.CODESTADO = M.CODESTADO)
	INNER JOIN INDICE AS I
		ON(I.CODMUNICIPIO = M.CODMUNICIPIO)
GROUP BY E.NOMEESTADO;

-- 10- Relatório de Todos IDHs da Bahia de 91 e 2000, inclusive com a
-- diferença entre os mesmos
EXPLAIN ANALYZE
WITH T91 AS 
(SELECT M.NOMEMUNICIPIO AS NOMEMUNICIPIO_91, I.IDH_GERAL, I.IDH_RENDA, I.IDH_LONGEVIDADE, I.IDH_EDUCACAO FROM MUNICIPIO AS M
	INNER JOIN INDICE AS I
		ON(M.CODMUNICIPIO = I.CODMUNICIPIO)
WHERE M.CODESTADO = (SELECT CODESTADO FROM ESTADO WHERE NOMEESTADO = 'Bahia') AND I.ANO = 1991),
T2000 AS
(SELECT M.NOMEMUNICIPIO AS NOMEMUNICIPIO_2000, I.IDH_GERAL, I.IDH_RENDA, I.IDH_LONGEVIDADE, I.IDH_EDUCACAO FROM MUNICIPIO AS M
	INNER JOIN INDICE AS I
		ON(M.CODMUNICIPIO = I.CODMUNICIPIO)
WHERE M.CODESTADO = (SELECT CODESTADO FROM ESTADO WHERE NOMEESTADO = 'Bahia') AND I.ANO = 2000)
SELECT
NOMEMUNICIPIO_91,
T91.IDH_GERAL,
T91.IDH_RENDA,
T91.IDH_LONGEVIDADE,
T91.IDH_EDUCACAO,
NOMEMUNICIPIO_2000,
T2000.IDH_GERAL,
T2000.IDH_RENDA,
T2000.IDH_LONGEVIDADE,
T2000.IDH_EDUCACAO,
T2000.IDH_GERAL - T91.IDH_GERAL AS DIF_IDH_GERAL,
T2000.IDH_RENDA - T91.IDH_RENDA AS DIF_IDH_RENDA,
T2000.IDH_LONGEVIDADE - T91.IDH_LONGEVIDADE AS DIF_IDH_LONGEVIDADE,
T2000.IDH_EDUCACAO - T91.IDH_EDUCACAO AS DIF_IDH_EDUCACAO FROM T91
	INNER JOIN T2000
		ON(NOMEMUNICIPIO_91 = NOMEMUNICIPIO_2000);

-- 11 - Relatório comparativo entre as médias dos IDHs de SC e AL,
-- de 2000 e 91

EXPLAIN ANALYZE
WITH TSC AS 
(SELECT I.ANO, I.IDH_GERAL, I.IDH_RENDA, I.IDH_LONGEVIDADE, I.IDH_EDUCACAO FROM ESTADO AS E
	INNER JOIN MUNICIPIO AS M
		ON(E.CODESTADO = M.CODESTADO)
	INNER JOIN INDICE AS I
		ON(M.CODMUNICIPIO = I.CODMUNICIPIO)
WHERE E.NOMEESTADO = 'Santa Catarina'),
TAL AS
(SELECT I.ANO, I.IDH_GERAL, I.IDH_RENDA, I.IDH_LONGEVIDADE, I.IDH_EDUCACAO FROM ESTADO AS E
	INNER JOIN MUNICIPIO AS M
		ON(E.CODESTADO = M.CODESTADO)
	INNER JOIN INDICE AS I
		ON(M.CODMUNICIPIO = I.CODMUNICIPIO)
WHERE E.NOMEESTADO = 'Alagoas')
SELECT
TSC.ANO,
AVG(TSC.IDH_GERAL) AS MEDIA_IDH_GERAL_SC,
AVG(TSC.IDH_RENDA) AS MEDIA_IDH_RENDA_SC,
AVG(TSC.IDH_LONGEVIDADE) AS MEDIA_IDH_LONGEVIDADE_SC,
AVG(TSC.IDH_EDUCACAO) AS MEDIA_IDH_EDUCACAO_SC,
AVG(TAL.IDH_GERAL) AS MEDIA_IDH_GERAL_AL,
AVG(TAL.IDH_RENDA) AS MEDIA_IDH_RENDA_AL,
AVG(TAL.IDH_LONGEVIDADE) AS MEDIA_IDH_LONGEVIDADE_AL,
AVG(TAL.IDH_EDUCACAO) AS MEDIA_IDH_EDUCACAO_AL
FROM TSC
	INNER JOIN TAL
		ON(TSC.ANO = TAL.ANO)
WHERE TSC.ANO = 1991 OR TAL.ANO = 2000
GROUP BY TSC.ANO;

-- MELHOR QUERY

EXPLAIN ANALYZE
WITH TSC AS 
(SELECT I.ANO, 
AVG(I.IDH_GERAL) AS MEDIA_IDH_GERAL_SC, AVG(I.IDH_RENDA) AS MEDIA_IDH_RENDA_SC, AVG(I.IDH_LONGEVIDADE) AS MEDIA_IDH_LONGEVIDADE_SC, AVG(I.IDH_EDUCACAO) AS MEDIA_IDH_EDUCACAO_SC 
FROM ESTADO AS E
	INNER JOIN MUNICIPIO AS M
		ON(E.CODESTADO = M.CODESTADO)
	INNER JOIN INDICE AS I
		ON(M.CODMUNICIPIO = I.CODMUNICIPIO)
WHERE E.NOMEESTADO = 'Santa Catarina' AND (I.ANO = 1991 OR I.ANO = 2000)
GROUP BY I.ANO),
TAL AS
(SELECT I.ANO, 
AVG(I.IDH_GERAL) AS MEDIA_IDH_GERAL_AL, AVG(I.IDH_RENDA) AS MEDIA_IDH_RENDA_AL, AVG(I.IDH_LONGEVIDADE) AS MEDIA_IDH_LONGEVIDADE_AL, AVG(I.IDH_EDUCACAO) AS MEDIA_IDH_EDUCACAO_AL 
FROM ESTADO AS E
	INNER JOIN MUNICIPIO AS M
		ON(E.CODESTADO = M.CODESTADO)
	INNER JOIN INDICE AS I
		ON(M.CODMUNICIPIO = I.CODMUNICIPIO)
WHERE E.NOMEESTADO = 'Alagoas' AND (I.ANO = 1991 OR I.ANO = 2000)
GROUP BY I.ANO)
SELECT TSC.ANO,
MEDIA_IDH_GERAL_SC, MEDIA_IDH_RENDA_SC, MEDIA_IDH_LONGEVIDADE_SC, MEDIA_IDH_EDUCACAO_SC,
MEDIA_IDH_GERAL_AL, MEDIA_IDH_RENDA_AL, MEDIA_IDH_LONGEVIDADE_AL, MEDIA_IDH_EDUCACAO_AL
FROM TSC
	INNER JOIN TAL
		ON(TSC.ANO = TAL.ANO);


