CREATE OR REPLACE TRIGGER Atualiza_Idx
	AFTER UPDATE ON Indice
	FOR EACH ROW
	WHEN (OLD.idh_educacao IS DISTINCT FROM NEW.idh_educacao
		OR OLD.idh_longevidade IS DISTINCT FROM NEW.idh_longevidade
		OR OLD.idh_geral IS DISTINCT FROM NEW.idh_geral)
	EXECUTE FUNCTION Nova_Auditoria();
	
-- Teste

UPDATE INDICE
SET IDH_EDUCACAO = 0.75
WHERE (CODMUNICIPIO, ANO) IN (
	SELECT CODMUNICIPIO, ANO FROM INDICE
	WHERE CODMUNICIPIO = 354880 AND ANO = 1991
);

SELECT * FROM AUDITORIA;
SELECT * FROM INDICE
WHERE CODMUNICIPIO = 354880 AND ANO = 1991;